 GET http://localhost:3000/customer

###
POST http://localhost:3000/customer
Content-Type: application/json

{
"name":,
"isGold":,
"Phone":
}

###
PUT http://localhost:3000/customer/
Content-Type: application/json

{
"name":,
"isGold":,
"Phone":
}

###
DELETE http://localhost:3000/customer/


