GET http://localhost:3000/genre

###
POST http://localhost:3000/genre
Content-Type: application/json
x-auth-token:

{
    "name":"comedy"
}

### 
PUT http://localhost:3000/genre/62b5ad859cf13fc1c94f218e
Content-Type: application/json

{
    "name":"horror"
}